const ROLE = {
  ADMIN : 'ADMIN',
  USER : 'user',
};

const STATUS = {
  ACTIVE : 'ACTIVE',
  INACTIVE : 'INACTIVE',
  PENDING : 'PENDING',
  APPROVED : 'APPROVED',
  REJECTED : 'REJECTED',
  COMPLETED : 'COMPLETED',
  FAILED : 'FAILED',
  PENDING_PAYMENT : 'PENDING_PAYMENT',
};

